# permissions for end users to edit assistedservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: assistedservice-editor-role
rules:
- apiGroups:
  - service.example.com
  resources:
  - assistedservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.example.com
  resources:
  - assistedservices/status
  verbs:
  - get
